name: deploy-base
description: Subgraph base deployment actions
inputs:
  chain:
    description: The chain to deploy the subgraph for
    required: true
  token:
    description: Authentication token
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Get yarn cache directory path
      shell: sh
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: install packages
      shell: sh
      run: yarn
    - uses: ./.github/actions/short-sha
      id: short-sha
    - name: Deploy subgraph
      shell: sh
      run: yarn subgraph deploy ${{ inputs.chain }}
      env:
        TOKEN: ${{ inputs.token }}
        VERSION: ${{ steps.short-sha.outputs.hash }}
