name: deploy-base
description: Subgraph base deployment actions
inputs:
  chain:
    description: The chain to deploy the subgraph for
    required: true
  deploy-key:
    description: Graph Node deploy key
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - name: install packages
      shell: sh
      run: yarn
    - uses: ./.github/actions/short-sha
      id: short-sha
    - name: Deploy subgraph
      shell: sh
      run: yarn subgraph deploy ${{ inputs.chain }}
      env:
        DEPLOY_KEY: ${{ inputs.deploy-key }}
        VERSION_LABEL: ${{ steps.short-sha.outputs.hash }}
