name: short-sha
description: Compute release version
runs:
  using: composite
  steps:
    - id: short-sha
      shell: sh
      run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_OUTPUT
outputs:
  hash:
    description: The short Git HEAD hash
    value: ${{ steps.short-sha.outputs.SHORT_SHA }}
    